server:
  port: 9001
spring:
  application:
    name: application-provider # 当前应用名
eureka:
  instance:
    instance-id: application-provider
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka #  服务中心地址，即在Eureka Server中配置暴露地址
