server:
  port: 9002
spring:
  application:
    name: application-consumer
eureka:
  instance:
    instance-id: application-consumer
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka #  服务中心地址，即在Eureka Server中配置暴露地址

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 指定Feign客户端连接提供者的超时时限，取决于网络环境
        readTimeout: 5000 # 指定Feign 客户端从请求到获取到提供者给出的响应的超时时限 取决于业务逻辑运算时间
  compression:
    request:
      enabled: true # 开启对请求的压缩
      min-request-size: 2048 # 指定启用压缩的最小文件大小
      mime-types: text/xml, application/xml
    response:
      enabled: true  # 开启对响应的压缩