server:
  port: 8085

spring:
  application:
    name: fraud
  datasource:
    username: maoqifan
    url: jdbc:postgresql://localhost:5432/fraud
    password: qq214031mm@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        fomat_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false