# 服务器
server:
  port: 8090
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
# 数据源
spring:
  datasource:
    ds1: #数据源1，默认数据源
      url: jdbc:mysql://localhost:3306/amq_db1?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: qq214031mm@
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
    ds2: #数据源2，默认数据源
      url: jdbc:mysql://localhost:3306/amq_db2?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: qq214031mm@
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      exclude: static/**
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    # 是否是内存模式
    in-memory: false
    pool:
      enabled: true
      # 最大连接数
      max-connections: 10
      # 连接空闲超时
      idle-timeout: 30000

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml


